---
title: "check calibration of mash fsr"
author: "Dongyue Xie"
date: "2021-03-26"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

Here we adjust the ED estimated covariance matrices using inverse information matrix.

```{r}
source('code/simulation/check_mash_lfsr.R')
```

```{r}
R = 5
n = 500
seed = 12345
```

## example 1

```{r}
u = toeplitz(c(1,0.5,0.2,0.2,0.1))
u[3:5,] = 0
u[,3:5] = 0
u
Ulist = list(U3 = u)
```




```{r,fig.width=12,fig.height=4}

  out = simu_mash_lfsr_info(Ulist,
                            pi = rep(1/length(Ulist),length(Ulist)),
                            N = n*length(Ulist),
                            npc=2,
                            info='full',
                            nreps=20,
                            mc.cores = 4,
                            seed=seed)

  plot.out(out,titles = paste("Adjusted with full info mat"))
  
  out = simu_mash_lfsr_info(Ulist,
                            pi = rep(1/length(Ulist),length(Ulist)),
                            N = n*length(Ulist),
                            npc=2,
                            info='diag',
                            nreps=20,
                            mc.cores = 4,
                            seed=seed)
  plot.out(out,titles = paste("Adjusted with diag info mat"))



```

## example 2

Try another example

```{r}
u = toeplitz(c(1,-0.7,0.2,0.1,0))
u[4:5,] = 0
u[,4:5] = 0
u
Ulist = list(U3 = u)
```



```{r,fig.width=12,fig.height=4}


  out = simu_mash_lfsr_info(Ulist,
                            pi = rep(1/length(Ulist),length(Ulist)),
                            N = n*length(Ulist),
                            npc=2,
                            info='full',
                            nreps=20,
                            mc.cores = 4,
                            seed=seed)
  plot.out(out,titles = paste("Adjusted with full info mat"))
  
  out = simu_mash_lfsr_info(Ulist,
                            pi = rep(1/length(Ulist),length(Ulist)),
                            N = n*length(Ulist),
                            npc=2,
                            info='diag',
                            nreps=20,
                            mc.cores = 4,
                            seed=seed)
  plot.out(out,titles = paste("Adjusted with diag info mat"))



```
