---
title: "ebci with and without point mass"
author: "Dongyue Xie"
date: "2022-01-23"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width = 12,fig.height = 4)
```


## Introduction

Here we compare the confidence interval returned by Empirikos when we set the Gaussian scale mixture prior class with/without point mass.

The settings of simulation are described [here](ebci.html)



```{r}
ebci0 = read.csv('output/ebci/lfsr_point_mass/spiky_lfsr.csv')
ebci = read.csv('output/ebci/lfsr_no_point_mass/spiky_lfsr.csv')
```


```{r}
#t, method, ground_truth_mean,   lower_mean,   upper_mean
# "dkw_scalemix"   "kde_scalemix"   "amari_scalemix" "dkw_locmix"     "kde_locmix"     "amari_locmix"  
target = seq(-5,0,by = 0.2)
method_list = c("dkw_scalemix","kde_scalemix","amari_scalemix")


plot_res = function(method,color,idx,ylim=c(0,1)){
  out = ebci[ebci$method == method,]
  out0 = ebci0[ebci0$method == method,]
  plot(out$t[idx],out$ground_truth_mean[idx],type='l',xlab='z',ylab=expression(paste('P(',mu>=0,'|',Z==z,')')), ylim=ylim,main=method)
  #axis(1,at=seq(-5,5,by=1))
  #axis(2,at=seq(0,1,by=0.1))
  polygon(c(rev(out$t[idx]), out$t[idx]), c(rev(out$upper_mean[idx]), out$lower_mean[idx]), col=color, border = NA)
  lines(out$t[idx],out$ground_truth_mean[idx])
  #lines(out$t,out$lower_mean,lty=2)
  #lines(out$t,out$upper_mean,lty=2)
  lines(out0$t[idx],out0$lower_mean[idx],lty=2)
  lines(out0$t[idx],out0$upper_mean[idx],lty=2)

  legend('topleft',c('Ground truth',"No point mass","Point mass"),
         lty=c(1,NA,2),bty="n",
         fill=c(NA,color,NA),
         border = rep(NA,3))

}

```

```{r}
par(mfrow=c(1,3))
plot_res(method = "dkw_scalemix",idx=1:26,color = rgb(1, 0.6, 0,0.5),ylim=c(0,1))
plot_res(method = "kde_scalemix",idx=1:26,color = rgb(1, 0.6, 0,0.5),ylim=c(0,1))
plot_res(method = "amari_scalemix",idx=1:26,color = rgb(1, 0.6, 0,0.5),ylim=c(0,1))
```


