---
title: "Look at 5 replicates in the simulation"
author: "Dongyue Xie"
date: "2022-01-23"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width = 10,fig.height = 15)
```


## Introduction

The settings of simulation are described [here](ebci.html). Here instead of looking at average, we look at the first 5 replicates.

## Scale mixture


```{r}
first5 = read.csv('output/ebci/lfsr_no_point_mass/spiky_lfsr_first5.csv')
head(first5)
plot_first5 = function(ebcidf,method,color,idx,ylim=c(0,1)){
  res = ebcidf[ebcidf$method == method,]
  for(i in 1:5){
    out = res[res$id==i,]
    plot(out$t[idx],out$ground_truth[idx],type='l',
         xlab='z',ylab=expression(paste('P(',mu>=0,'|',Z==z,')')),
       ylim=ylim)
    polygon(c(rev(out$t[idx]), out$t[idx]), c(rev(out$upper[idx]), out$lower[idx]), col=color, border = NA)
    lines(out$t[idx],out$ground_truth[idx],col='grey50')
    
    for(j in 1:3){
      lines(target[idx],PosProb[i,idx,j],lty=j+1)
      }
  #abline(h=0.01,lty=3,col='grey40')
  #abline(h=0.05,lty=3,col='grey40')
  legend('topleft',c('Ground truth',paste('nullweight = ',c(1,10,100)),method),
         lty=c(1,2,3,4,NA),bty="n",
         fill=c(rep(NA,4), color),
         border = rep(NA,5),
         x.intersp=c(rep(1,4),1))
  
  }
}

```

run ash, use the same z scores(saved from Julia)

```{r}
library(ashr)
n = 5000
target = seq(-5,5,by=0.2)


a = 0.1
mixsd = 0.1
while(a<15.6){
  a = a*1.1
  mixsd = c(mixsd,a)
}


nullweights = c(1,10,100)
PosProb = array(dim=c(5,length(target),length(nullweights)))
for(i in 1:5){
  z = read.csv(paste('output/ebci/lfsr_no_point_mass/Zs_rep',i,'.csv',sep=''))$Column1
  for(j in 1:length(nullweights)){
    ghat = ash(z,s=1,mixcompdist = 'normal',pointmass = FALSE, optmethod='mixSQP',prior = 'nullbiased',mixsd = mixsd,nullweight=nullweights[j])$fitted_g
    res = ash(target,s=1,g=ghat,fixg=TRUE)
    PosProb[i,,j] = res$result$PositiveProb
  }
}

```

```{r}
par(mfrow=c(3,2))
plot_first5(first5,method = "dkw_scalemix",idx=1:11,color = rgb(1, 0.6, 0,0.5),ylim=c(0,0.1))
```

```{r}
par(mfrow=c(3,2))
plot_first5(first5,method = "kde_scalemix",idx=1:11,color = rgb(0.4, 0, 0,0.4),ylim=c(0,0.1))
```

```{r}
par(mfrow=c(3,2))
plot_first5(first5,method = "amari_scalemix",idx=1:11,color = rgb(0, 0, 0.8,0.4),ylim=c(0,0.08))
```


## Location mixture

```{r}
par(mfrow=c(3,2))
plot_first5(first5,method = "dkw_locmix",idx=1:11,color = rgb(1, 0.6, 0,0.5),ylim=c(0,0.1))
```

```{r}
par(mfrow=c(3,2))
plot_first5(first5,method = "kde_locmix",idx=1:11,color = rgb(0.4, 0, 0,0.4),ylim=c(0,0.1))
```

```{r}
par(mfrow=c(3,2))
plot_first5(first5,method = "amari_locmix",idx=1:11,color = rgb(0, 0, 0.8,0.4),ylim=c(0,0.08))
```

