---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

## Overview

This project explores `masking` in multiple testing.

## Analysis

0. [Try AdaPT](tryAdaPT.html)
1. [masked mash on FDR control, t, uniform and normal priors](maskedmashFDR_prior.html)


## Others

1. [Fix the issue of using low rank matrix, by an EB procedure](mashFIX.html)
2. [Fix the issue of using low rank matrix, large N](mashfixLargeN.html)
3. [Fix the issue of using low rank matrix, general case](mashFIXv_i.html)
4. [On the null distribution in lfdr](empirical_null.html)
5. [Checking the calibration of mash lfsr](check_mash_fsr2.html),  [adjust using info mat](check_mash_fsr_info.html)
6. [on lfsr and point mass](lfsr_pointmass.html)
7. [Checking the calibration of mash lfsr, no point mass in data-generation](check_mash_fsr_info_no_point_mass.html)
8. [Nonparametric empirical Bayes confidence interval explorations](nebci.html)
