---
title: "Fix the mash issue with low rank matrix"
author: "Dongyue Xie"
date: "2021-02-25"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


```{r,message=FALSE,results=FALSE}
library(devtools)
load_all('code/mashr/')
library(mvtnorm)
source('code/misc/genData.R')
files.sources = list.files('code/maskedmashr/')
sapply(files.sources, function(x){source(paste('code/maskedmashr/',x,sep=''))})
```


### nk = 100

```{r}
signal_sd = sqrt(3)
u1 = c(1,1,1,0,0,0,0,0)
u2 = 1-u1
R = length(u1)
cov1 = tcrossprod(u1)
#cov1[1,1] = 1
cov2 = tcrossprod(u2)
#cov2[5,5] = 1
#cov2[4,4] = 1

U = list(U1=cov1,U2=cov2)
#U = list(U1=cov1)
U
set.seed(12345)
n=100
simdata = genData(n,U,signal_sd)
data = mash_set_data(simdata$Bhat,simdata$Shat)
U.c = cov_canonical(data)
out_mash_true = mash(data, c(U.c,U),verbose = F)

m.1by1 = mash_1by1(data)
strong = get_significant_results(m.1by1)
U.pca = cov_pca(data,3,strong)
U.ed = bovy_wrapper(data,U.pca,subset=strong)
U.est = U.ed$Ulist
#fdp_power(out_mash_true$result$lfsr,simdata$B)
out_mash = mash_wrapper(data$Bhat, Shat = data$Shat,verbose = F,adjust = 'NULL',U.ed = U.ed,n.ed=length(strong))
#fdp_power(out_mash$result$lfsr,simdata$B)
out_mash_prior = mash_wrapper(data$Bhat, Shat = data$Shat,verbose = F,adjust = 'prior',U.ed = U.ed,n.ed=length(strong))

out_mash_lb = mash_wrapper(data$Bhat, Shat = data$Shat,verbose = F,adjust = 'lb',U.ed = U.ed,n.ed=length(strong))

fp = cbind(unlist(fdp_power(out_mash_true$result$lfsr,simdata$B)),
      unlist(fdp_power(out_mash$result$lfsr,simdata$B)),
      unlist(fdp_power(out_mash_prior$result$lfsr,simdata$B)),
      unlist(fdp_power(out_mash_lb$result$lfsr,simdata$B)))

colnames(fp) = c("True.U","U.ed","U.ed.prior","U.ed.lb")
knitr::kable(round(fp,3),caption = "Set lfsr level at 0.05")

cm = cbind(c(cor(c(out_mash_true$result$lfsr),c(out_mash$result$lfsr)),rmse(c(out_mash_true$result$lfsr),c(out_mash$result$lfsr))),
      c(cor(c(out_mash_prior$result$lfsr),c(out_mash$result$lfsr)),rmse(c(out_mash_prior$result$lfsr),c(out_mash$result$lfsr))),
      c(cor(c(out_mash_lb$result$lfsr),c(out_mash$result$lfsr)),rmse(c(out_mash_lb$result$lfsr),c(out_mash$result$lfsr))))

rownames(cm) = c("cor","rmse")
colnames(cm) = c("U.ed","U.ed.prior","U.ed.lb")

knitr::kable(round(cm,3),caption = "correlation and rmse between lfsr from model with true U and model with estimated U")

```


### nk = 500

```{r}
n=500
simdata = genData(n,U,signal_sd)
data = mash_set_data(simdata$Bhat,simdata$Shat)
U.c = cov_canonical(data)
out_mash_true = mash(data, c(U.c,U),verbose = F)

m.1by1 = mash_1by1(data)
strong = get_significant_results(m.1by1)
U.pca = cov_pca(data,3,strong)
U.ed = bovy_wrapper(data,U.pca,subset=strong)
U.est = U.ed$Ulist
#fdp_power(out_mash_true$result$lfsr,simdata$B)
out_mash = mash_wrapper(data$Bhat, Shat = data$Shat,verbose = F,adjust = 'NULL',U.ed = U.ed,n.ed=length(strong))
#fdp_power(out_mash$result$lfsr,simdata$B)
out_mash_prior = mash_wrapper(data$Bhat, Shat = data$Shat,verbose = F,adjust = 'prior',U.ed = U.ed,n.ed=length(strong))

out_mash_lb = mash_wrapper(data$Bhat, Shat = data$Shat,verbose = F,adjust = 'lb',U.ed = U.ed,n.ed=length(strong))

fp = cbind(unlist(fdp_power(out_mash_true$result$lfsr,simdata$B)),
      unlist(fdp_power(out_mash$result$lfsr,simdata$B)),
      unlist(fdp_power(out_mash_prior$result$lfsr,simdata$B)),
      unlist(fdp_power(out_mash_lb$result$lfsr,simdata$B)))

colnames(fp) = c("True.U","U.ed","U.ed.prior","U.ed.lb")
knitr::kable(round(fp,3),caption = "Set lfsr level at 0.05")

cm = cbind(c(cor(c(out_mash_true$result$lfsr),c(out_mash$result$lfsr)),rmse(c(out_mash_true$result$lfsr),c(out_mash$result$lfsr))),
      c(cor(c(out_mash_prior$result$lfsr),c(out_mash$result$lfsr)),rmse(c(out_mash_prior$result$lfsr),c(out_mash$result$lfsr))),
      c(cor(c(out_mash_lb$result$lfsr),c(out_mash$result$lfsr)),rmse(c(out_mash_lb$result$lfsr),c(out_mash$result$lfsr))))

rownames(cm) = c("cor","rmse")
colnames(cm) = c("U.ed","U.ed.prior","U.ed.lb")

knitr::kable(round(cm,3),caption = "correlation and rmse between lfsr from model with true U and model with estimated U")

```

### nk = 1000

```{r}
n=1000
simdata = genData(n,U,signal_sd)
data = mash_set_data(simdata$Bhat,simdata$Shat)
U.c = cov_canonical(data)
out_mash_true = mash(data, c(U.c,U),verbose = F)

m.1by1 = mash_1by1(data)
strong = get_significant_results(m.1by1)
U.pca = cov_pca(data,3,strong)
U.ed = bovy_wrapper(data,U.pca,subset=strong)
U.est = U.ed$Ulist
#fdp_power(out_mash_true$result$lfsr,simdata$B)
out_mash = mash_wrapper(data$Bhat, Shat = data$Shat,verbose = F,adjust = 'NULL',U.ed = U.ed,n.ed=length(strong))
#fdp_power(out_mash$result$lfsr,simdata$B)
out_mash_prior = mash_wrapper(data$Bhat, Shat = data$Shat,verbose = F,adjust = 'prior',U.ed = U.ed,n.ed=length(strong))

out_mash_lb = mash_wrapper(data$Bhat, Shat = data$Shat,verbose = F,adjust = 'lb',U.ed = U.ed,n.ed=length(strong))

fp = cbind(unlist(fdp_power(out_mash_true$result$lfsr,simdata$B)),
      unlist(fdp_power(out_mash$result$lfsr,simdata$B)),
      unlist(fdp_power(out_mash_prior$result$lfsr,simdata$B)),
      unlist(fdp_power(out_mash_lb$result$lfsr,simdata$B)))

colnames(fp) = c("True.U","U.ed","U.ed.prior","U.ed.lb")
knitr::kable(round(fp,3),caption = "Set lfsr level at 0.05")

cm = cbind(c(cor(c(out_mash_true$result$lfsr),c(out_mash$result$lfsr)),rmse(c(out_mash_true$result$lfsr),c(out_mash$result$lfsr))),
      c(cor(c(out_mash_prior$result$lfsr),c(out_mash$result$lfsr)),rmse(c(out_mash_prior$result$lfsr),c(out_mash$result$lfsr))),
      c(cor(c(out_mash_lb$result$lfsr),c(out_mash$result$lfsr)),rmse(c(out_mash_lb$result$lfsr),c(out_mash$result$lfsr))))

rownames(cm) = c("cor","rmse")
colnames(cm) = c("U.ed","U.ed.prior","U.ed.lb")

knitr::kable(round(cm,3),caption = "correlation and rmse between lfsr from model with true U and model with estimated U")

```

### nk = 5000

```{r}
n=5000
simdata = genData(n,U,signal_sd)
data = mash_set_data(simdata$Bhat,simdata$Shat)
U.c = cov_canonical(data)
out_mash_true = mash(data, c(U.c,U),verbose = F)

m.1by1 = mash_1by1(data)
strong = get_significant_results(m.1by1)
U.pca = cov_pca(data,3,strong)
U.ed = bovy_wrapper(data,U.pca,subset=strong)
#fdp_power(out_mash_true$result$lfsr,simdata$B)
out_mash = mash_wrapper(data$Bhat, Shat = data$Shat,verbose = F,adjust = 'NULL',U.ed = U.ed,n.ed=length(strong))
#fdp_power(out_mash$result$lfsr,simdata$B)
out_mash_prior = mash_wrapper(data$Bhat, Shat = data$Shat,verbose = F,adjust = 'prior',U.ed = U.ed,n.ed=length(strong))

out_mash_lb = mash_wrapper(data$Bhat, Shat = data$Shat,verbose = F,adjust = 'lb',U.ed = U.ed,n.ed=length(strong))

fp = cbind(unlist(fdp_power(out_mash_true$result$lfsr,simdata$B)),
      unlist(fdp_power(out_mash$result$lfsr,simdata$B)),
      unlist(fdp_power(out_mash_prior$result$lfsr,simdata$B)),
      unlist(fdp_power(out_mash_lb$result$lfsr,simdata$B)))

colnames(fp) = c("True.U","U.ed","U.ed.prior","U.ed.lb")
knitr::kable(round(fp,3),caption = "Set lfsr level at 0.05")

cm = cbind(c(cor(c(out_mash_true$result$lfsr),c(out_mash$result$lfsr)),rmse(c(out_mash_true$result$lfsr),c(out_mash$result$lfsr))),
      c(cor(c(out_mash_prior$result$lfsr),c(out_mash$result$lfsr)),rmse(c(out_mash_prior$result$lfsr),c(out_mash$result$lfsr))),
      c(cor(c(out_mash_lb$result$lfsr),c(out_mash$result$lfsr)),rmse(c(out_mash_lb$result$lfsr),c(out_mash$result$lfsr))))

rownames(cm) = c("cor","rmse")
colnames(cm) = c("U.ed","U.ed.prior","U.ed.lb")

knitr::kable(round(cm,3),caption = "correlation and rmse between lfsr from model with true U and model with estimated U")
```


