---
title: "Try AdaPT"
author: "Dongyue Xie"
date: "2020-11-04"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

See [section 5.2.1](https://arxiv.org/abs/1609.06035) in the paper for the first simulation example.

1. what if use glm instead of gam; 2. what if the side information $x$ contributes no information?

```{r}
library(adaptMT)
summary_adapt <- function(adapt, H0, pvals){
    results <- apply(adapt$s, 2, function(s){
        tmp <- (pvals <= s)
        nfrej <- sum(tmp[which(H0==0)], na.rm = TRUE)
        ntrej <- sum(tmp[which(H0==1)], na.rm = TRUE)
        return(c(nfrej, ntrej))
    })
    nfrej <- as.numeric(results[1, ])
    ntrej <- as.numeric(results[2, ])
    nrej <- nfrej + ntrej
    FDP <- nfrej / pmax(nrej, 1)
    power <- ntrej / max(sum(H0),1)
    df <- data.frame(nrej = nrej, FDP = FDP, power = power)
    return(df)
}
summary_BH <- function(pvals, H0,
                       alphas = seq(0.01, 0.3, 0.01)){
    n <- length(pvals)
    results <- sapply(alphas, function(alpha){
        khat <- max(c(0, which(sort(pvals) <= alpha * (1:n) / n)))
        alpha <- alpha * khat / n
        nfrej <- sum(pvals[which(H0==0)] < alpha, na.rm = TRUE)
        ntrej <- sum(pvals[which(H0==1)] < alpha, na.rm = TRUE)
        return(c(nfrej, ntrej))
    })
    nfrej <- as.numeric(results[1, ])
    ntrej <- as.numeric(results[2, ])
    nrej <- nfrej + ntrej
    FDP <- nfrej / pmax(nrej, 1)
    power <- ntrej / max(sum(H0), 1)
    df <- data.frame(nrej = nrej, FDP = FDP, power = power)
    return(df)
}
```


example in paper use glm 

```{r}
set.seed(12345)
x1 <- seq(-100, 100, length.out = 50)
x2 <- seq(-100, 100, length.out = 50)
x <- expand.grid(x1, x2)
colnames(x) <- c("x1", "x2")
pi_formula <- mu_formula <- "s(x1, x2)"
#alphas <- seq(0.01, 0.23, 0.04)
alphas = c(0.01,0.05,0.1,0.2)
## Case 1: a circle in the center
H0 <- apply(x, 1, function(coord){sum(coord^2) < 900})
#H0 = rbinom(n,1,0.0656)
mu <- ifelse(H0, 2, 0)
n <- length(mu)
n1 <- n2 <- floor(sqrt(n))
m <- length(alphas)
z <- rnorm(n) + mu
pvals <- 1 - pnorm(z)
res_glm <- try(adapt_glm(x, pvals,pi_formulas = "x1 + x2",
                      mu_formulas = "x1 + x2",alphas = alphas,verbose=list(print=F,fit=F,ms=F)))
res_gam <- try(adapt_gam(x, pvals,pi_formulas = pi_formula,
                      mu_formulas = mu_formula,alphas = alphas,niter_fit = 5))
summary_res_glm = summary_adapt(res_glm,H0,pvals)
summary_res_gam = summary_adapt(res_gam,H0,pvals)
summary_bh = summary_BH(pvals,H0,alphas)
print(cbind(alphas,summary_res_glm))
print(cbind(alphas,summary_res_gam))
print(cbind(alphas,summary_bh))
plot(alphas,summary_res_glm$FDP,type='l',ylim=c(0,0.25),ylab='FDP',xlab='target FDR level')
lines(alphas,summary_res_gam$FDP,col=2)
lines(alphas,summary_bh$FDP,col=3)
abline(a=0,b=1,lty=2)
legend('bottomright',c('adapt_glm','adapt_gam','BH'),lty=c(1,1,1),col=c(1,2,3))

plot(alphas,summary_res_glm$power,type='l',ylim=c(0,1),ylab='power',xlab='target FDR level')
lines(alphas,summary_res_gam$power,col=2)
lines(alphas,summary_bh$power,col=3)
legend('right',c('adapt_glm','adapt_gam','BH'),lty=c(1,1,1),col=c(1,2,3))
```


random generate $H$. 

```{r}
set.seed(12345)
x1 <- seq(-100, 100, length.out = 50)
x2 <- seq(-100, 100, length.out = 50)
x <- expand.grid(x1, x2)
xx = data.frame(x1 = rep(1,2500),x2 = rep(1,2500))
colnames(x) <- c("x1", "x2")
#pi_formula <- mu_formula <- "s(x1, x2)"
#alphas <- seq(0.01, 0.23, 0.04)
alphas = c(0.01,0.05,0.1,0.2,0.3)
## Case 1: a circle in the center
#H0 <- apply(x, 1, function(coord){sum(coord^2) < 900})
n <- nrow(x)
H0 = rbinom(n,1,0.1)
mu <- ifelse(H0, 2, 0)
z <- rnorm(n) + mu
pvals <- 1 - pnorm(z)
res <- try(adapt_glm(x, pvals,pi_formulas = "x1 + x2",
                      mu_formulas = "x1 + x2",alphas = alphas,verbose=list(print=F,fit=F,ms=F)))
res_same <- try(adapt_glm(xx, pvals,pi_formulas = "x1 + x2",
                      mu_formulas = "x1 + x2",alphas = alphas,verbose=list(print=F,fit=F,ms=F)))
summary_res_glm = summary_adapt(res,H0,pvals)
summary_res_same_glm = summary_adapt(res_same,H0,pvals)
summary_bh = summary_BH(pvals,H0,alphas)
print(cbind(alphas,summary_res_glm))
print(cbind(alphas,summary_res_same_glm))
#print(cbind(alphas,summary_res_gam))
print(cbind(alphas,summary_bh))
plot(alphas,summary_res_glm$FDP,type='l',ylim=c(0,0.3),ylab='FDP',xlab='target FDR level')
lines(alphas,summary_res_same_glm$FDP,col=2)
lines(alphas,summary_bh$FDP,col=3)
abline(a=0,b=1,lty=2)
legend('topleft',c('adapt_glm','adapt_glm_no_x','BH'),lty=c(1,1,1),col=c(1,2,3))

plot(alphas,summary_res_glm$power,type='l',ylim=c(0,1),ylab='power',xlab='target FDR level')
lines(alphas,summary_res_same_glm$power,col=2)
lines(alphas,summary_bh$power,col=3)
legend('topleft',c('adapt_glm','adapt_glm_no_x','BH'),lty=c(1,1,1),col=c(1,2,3))
```

